INSERT INTO users (NAME_USER, LASTNAME_USER, EMAIL_USER, PASSWORD_USER, ENABLED_USER, IMAGE_USER) VALUES ('SERGIO', 'RAMIREZ', 'ramirezsergiod1999@outlook.com', '$2a$10$arHYHaoby/Be3MA0swtBw.77B9IyiplLTHpHjuepqKTjf8PCqHvFW', true, 'avatar-ninja.png')
INSERT INTO users (NAME_USER, LASTNAME_USER, EMAIL_USER, PASSWORD_USER, ENABLED_USER, IMAGE_USER) VALUES ('DARIO', 'RAMIREZ', 'dalaser20@hotmail.com', '$2a$10$B0mQRh2zpojDihRBRc3MZ.y12pVIPedhoUVH3Ja1yAAOSpgW.F9iC', true, 'avatar-ninja.png');
INSERT INTO users (NAME_USER, LASTNAME_USER, EMAIL_USER, PASSWORD_USER, ENABLED_USER, IMAGE_USER) VALUES ('LAURA', 'RAMIREZ', 'ramirezlauran@hotmail.com', '$2a$10$B0mQRh2zpojDihRBRc3MZ.y12pVIPedhoUVH3Ja1yAAOSpgW.F9iC', true, 'avatar-ninja.png');
INSERT INTO users (NAME_USER, LASTNAME_USER, EMAIL_USER, PASSWORD_USER, ENABLED_USER, IMAGE_USER) VALUES ('MABEL', 'RAMIREZ', 'silviamabel1945@hotmail.com', '$2a$10$B0mQRh2zpojDihRBRc3MZ.y12pVIPedhoUVH3Ja1yAAOSpgW.F9iC', true, 'avatar-ninja.png');
INSERT INTO users (NAME_USER, LASTNAME_USER, EMAIL_USER, PASSWORD_USER, ENABLED_USER, IMAGE_USER) VALUES ('RAQUEL', 'SANTIN', 'raquelsantin1995@hotmail.com', '$2a$10$B0mQRh2zpojDihRBRc3MZ.y12pVIPedhoUVH3Ja1yAAOSpgW.F9iC', true, 'avatar-ninja.png');

INSERT INTO authorities (ROLE_AUTHORITY, USER_ID) VALUES ('ADMIN', '1');
INSERT INTO authorities (ROLE_AUTHORITY, USER_ID) VALUES ('USER', '2');
INSERT INTO authorities (ROLE_AUTHORITY, USER_ID) VALUES ('USER', '3');
INSERT INTO authorities (ROLE_AUTHORITY, USER_ID) VALUES ('USER', '4');
INSERT INTO authorities (ROLE_AUTHORITY, USER_ID) VALUES ('USER', '5');

INSERT INTO groups (TOKEN_GROUP) VALUES ('FAMILIARAMIREZ');
INSERT INTO groups (TOKEN_GROUP) VALUES ('FAMILIASANTIN');

INSERT INTO animals (NAME_ANIMAL, BIRTHDATE_ANIMAL, WEIGHT_ANIMAL, TYPE_ANIMAL, IMAGE_ANIMAL, ID_GROUP) VALUES ('DUKE', '2006-11-09', 55.2, 'PERRO', null, 1);
INSERT INTO animals (NAME_ANIMAL, BIRTHDATE_ANIMAL, WEIGHT_ANIMAL, TYPE_ANIMAL, IMAGE_ANIMAL,  ID_GROUP) VALUES ('GRETA', '2012-08-03', 55.2, 'PERRO', null, 1);
INSERT INTO animals (NAME_ANIMAL, BIRTHDATE_ANIMAL, WEIGHT_ANIMAL, TYPE_ANIMAL, IMAGE_ANIMAL,  ID_GROUP) VALUES ('BRUNO', '2013-01-08', 55.2, 'PERRO', null, 2);
INSERT INTO animals (NAME_ANIMAL, BIRTHDATE_ANIMAL, WEIGHT_ANIMAL, TYPE_ANIMAL, IMAGE_ANIMAL,  ID_GROUP) VALUES ('RENZO', '2012-05-23', 55.2, 'PERRO', null, 2);
INSERT INTO animals (NAME_ANIMAL, BIRTHDATE_ANIMAL, WEIGHT_ANIMAL, TYPE_ANIMAL, IMAGE_ANIMAL,  ID_GROUP) VALUES ('MANU', '2006-12-03', 55.2, 'TORTUGA', null, 1);
INSERT INTO animals (NAME_ANIMAL, BIRTHDATE_ANIMAL, WEIGHT_ANIMAL, TYPE_ANIMAL, IMAGE_ANIMAL,  ID_GROUP) VALUES ('DONA', '2006-03-12', 55.2, 'TORTUGA', null, 1);